### ISSUE TITLE
How to detect if card is battery powered or usb powered?

### ISSUE THREAD

**Issue by Paranoramix** [Xinyuan-LilyGO/LilyGO-T-SIM7600X#12]
I am wondering how to detect if the card is powered by USB or if it is running on battery. In schematics, I don't see anything that would allow this. 

Can you confirm this for me?

thanks in advance

**Comment by LilyGO** [comment]
Hello, are you asking whether the SIM card is battery powered or USB powered?

**Comment by Paranoramix** [comment]
Hello,

Thanks for your anwser. 
After reading again schematics, I saw the ADC(35) can be used to check if the card is battery powered or USB powered.

```
if (analogRead(35) > 0) {
Serial.println("Battery Powered!");
} else {
Serial.println("USB Powered!");
}
```

Basically, I would like know the state of the battery (is charging, charged, or in use). Is it possible?

Regards

**Comment by LilyGO** [comment]
You can check the charging status through the indicato
![1](https://user-images.githubusercontent.com/31160602/148373545-b95ae027-fdbf-401b-83ac-63915d661658.png)
r

**Comment by Paranoramix** [comment]
OK, thanks, but this is just a visual indicator.
I meant programmatically ;)

**Comment by rayenbouzidi** [comment]
hello bro do you solve this problem ?
