### ISSUE TITLE
Auxilary Antenna

### ISSUE THREAD

**Issue by AirTobe91** [Xinyuan-LilyGO/LilyGO-T-SIM7600X#15]
Hello,
I have a question regarding the antennas of the module.
There is a GPS port, Main port and Aux port.
The GPS port and Main port are self explaining.

For what can the Aux port be used?
Is it possible to add a second LTE antenna for better signal?
Or what can the Aux port be used for?

Thanks!

**Comment by LilyGO** [comment]
since there are many high bands in the designing of LTE-TDD, such as band38, band40 and band41.    Because of the high insert loss of the RF 
cable and layout lines, the receiver sensitivity of these bands above will have risk to meet the 
authentication without the diversity antenna.

**Comment by LilyGO** [comment]
since there are many high bands in the designing of LTE-TDD, such as band38, band40 and band41.    Because of the high insert loss of the RF cable and layout lines, the receiver sensitivity of these bands above will have risk to meet the authentication without the diversity antenna.
