### ISSUE TITLE
Is it possible to programme with ESP-IDF for OTA functionality

### ISSUE THREAD

**Issue by FalconBFR** [Xinyuan-LilyGO/LilyGO-T-SIM7600X#4]
Hi! I have seen reviews of this board but it seems like it is only programmable with the ardunio ide. Is it possible to use ESP-IDF or micro python for this board? Thanks!

你好！請問可以用ESP-IDF或micropython,取代ardunio ide編程嗎？謝謝

**Comment by LilyGO** [comment]
Yes, you can use ESP-IDF and MicroPython
