### ISSUE TITLE
development board has two IMEI

### ISSUE THREAD

**Issue by freiregtr** [Xinyuan-LilyGO/LilyGO-T-SIM7600X#48]
hello!

I have a question because I can't get the development board to activate. On the one hand, an IMEI appears on the cover of the device that I have already registered in my country. I have already done this process with other boards and I have no problems, but with the same example of tinygsm that you provide the imei is another. The strangest thing about all this is that the board was supposedly activated in my country in 2022, but I just bought it in 2023. I need to know why there are differences between an IMEI between what the top of the chip indicates and what it tells me the function modem.getIMEI()

**Comment by freiregtr** [comment]
Just to clarify, I have two development boards, a ttgo 7600g-h which is the one I'm having problems with and a 7000g, I subjected them both to the same tests, however the 7000g development board matches the IMEI indicated on the development and what the getImei function returns

I leave photographs to show the problem with the development board


![simcom-7600-1](https://user-images.githubusercontent.com/34633333/235939286-9d13103f-0f60-4589-97e9-d5e603ecff85.jpg)

![simcom-7600-2](https://user-images.githubusercontent.com/34633333/235939331-7defc6ad-b503-4a22-a7d5-8bf19c440a08.jpg)

![simcom-7000-1](https://user-images.githubusercontent.com/34633333/235939358-7cc12d8f-a14a-4f16-8715-85f4ed1e79d4.jpg)

![simcom-7000-2](https://user-images.githubusercontent.com/34633333/235939383-549cc9b1-8484-4cab-a3aa-e8cc6d3b1e7d.jpg)

**Comment by lewisxhe** [comment]
This is because the IMEI was not restored due to a missing test program. You can use AT+SIMEI=(adjust the IMEI on the demodulator sticker to restore)

**Comment by freiregtr** [comment]
> 

How do I do that? because the first time I bought a development board from you this did not happen to me

**Comment by freiregtr** [comment]
> This is because the IMEI was not restored due to a missing test program. You can use AT+SIMEI=(adjust the IMEI on the demodulator sticker to restore)

How do I do that? because the first time I bought a development board from you this did not happen to me

**Comment by lewisxhe** [comment]
After writing to [ATdebug](https://github.com/Xinyuan-LilyGO/T-SIM7600X/tree/master/examples/ATdebug), use command
```
AT+SIMEI=(IMEI number on the sticker)


```
Just write in the correct IMEI number.

**Comment by freiregtr** [comment]
> After writing to [ATdebug](https://github.com/Xinyuan-LilyGO/T-SIM7600X/tree/master/examples/ATdebug), use command
> 
> ```
> AT+SIMEI=(IMEI number on the sticker)
> ```
> 
> Just write in the correct IMEI number.

Its works. Just a few data to this issue: AT+SIMEI? to know your imei, AT+SIMEI=123456789123456 for change imei.
Thanks for taking your time.
