### ISSUE TITLE
gps code sample work

### ISSUE THREAD

**Issue by tradexsrl** [Xinyuan-LilyGO/LilyGO-T-SIM7600X#5]
Hi , i get this board but i have found very few documentation, have you got a working code for gps?
for the version 7000G i had to modify tinygsm library otherwise i get no response from gps satellite
please let me know

**Comment by LilyGO** [comment]
> Hi , i get this board but i have found very few documentation, have you got a working code for gps?
> for the version 7000G i had to modify tinygsm library otherwise i get no response from gps satellite
> please let me know

Allfunctions.ino has all the tests.

**Comment by tradexsrl** [comment]
ok i'm using this but i get negative latitude and negative longitude with .getps() , if i delete the minus sign everythings is ok
instead the gpsraw() get positive latitude and longitude.......

**Comment by tradexsrl** [comment]
i have used that .ino file but it doesn't work correctly , you need to make a modification in the tinygsm library as written in #566 issue

**Comment by osugiw** [comment]
Im using SIM7600GH and have problem with GPS, I also using AllFunctions.ino and it couldn't retrieve the coordinates like this:
![image](https://user-images.githubusercontent.com/51029305/132657986-f5ba436f-4c59-4e9d-8814-e462b921fefa.png)

Is there any solutions to this?

**Comment by tradexsrl** [comment]
are you inside or outside? inside of a building these gps never works , to make it work you need to use an external antenna and place it outside the window , then you need also to modify the library as written in #566 issue.
first time you locate it takes at least 3-5 minutes

**Comment by osugiw** [comment]
> are you inside or outside? inside of a building these gps never works , to make it work you need to use an external antenna and place it outside the window , then you need also to modify the library as written in #566 issue.
> first time you locate it takes at least 3-5 minutes

yeah it's first time to power on, true i'm inside building but near to window and already attach external antenna.. Finally the coordinates appears after some minutes. But why it took so long to get the coordinates any idea? I've tried using SIM7000C to retrieve coordinates, it just need some seconds to get the coordinates.

**Comment by osugiw** [comment]
> are you inside or outside? inside of a building these gps never works , to make it work you need to use an external antenna and place it outside the window , then you need also to modify the library as written in #566 issue.
> first time you locate it takes at least 3-5 minutes

could you share the url for #566 issue? maybe it could help on other problems

**Comment by tradexsrl** [comment]
for external antenna i mean not the one that comes with the board , i have to buy one on amazon
in my experience also the sim7000 takes some times to locate.
this is the url: https://github.com/vshymanskyy/TinyGSM/issues/566

**Comment by osugiw** [comment]
I bought from the aliexpress the external antenna is included.
![image](https://user-images.githubusercontent.com/51029305/132664989-f847953b-322c-433c-9e64-a32f599d87c2.png)

I think it depends on type of the external antenna, because I use this antenna on SIM 7000C and just took some seconds to get the coordinates
![image](https://user-images.githubusercontent.com/51029305/132665164-2babbb6d-074f-4cd5-bcfb-f3bc93caeb6d.png)

Thanks for the url!

**Comment by tradexsrl** [comment]
the small one marked 1568R-A that comes with the board with simcom7600 never worked inside , i use exactly the same black antenna with long cable and it is better

**Comment by osugiw** [comment]
> the small one marked 1568R-A that comes with the board with simcom7600 never worked inside , i use exactly the same black antenna with long cable and it is better

Got it! Thanks sir for the sharing it helps a lot!
