### ISSUE TITLE
schematic 

### ISSUE THREAD

**Issue by sq4cvh** [Xinyuan-LilyGO/LilyGO-T-SIM7600X#6]
Can you publish the schematic of the device (as for T-Call), I am especially interested in the ability to control converters, power consumption in deep-sleep mode

**Comment by gorghino** [comment]
Up @LilyGO

**Comment by LilyGO** [comment]
Hello, [this is the schematic](https://github.com/Xinyuan-LilyGO/LilyGO-T-SIM7600X/blob/master/schematic/T54_SIM7600_20201012.pdf)
